# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StAugustineTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StAugustineTestApp
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'Firebase/Database'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Firebase/Functions'
pod 'Firebase/Messaging'
pod 'Fabric', '~> 1.9.0'
pod 'Crashlytics', '~> 3.12.0'
pod 'Firebase/InAppMessagingDisplay'
pod 'Firebase/RemoteConfig'
pod 'CropViewController'
pod "Floaty", "~> 4.1.0"
pod 'Firebase/MLVision'
pod 'Firebase/MLVisionBarcodeModel'
pod 'SwiftSoup'

  target 'StAugustineTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StAugustineTestAppUITests' do
    # Pods for testing
  end

end
